

// ------------------------------------------------------------------------------
//  <auto-generated>
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated. 
//  </auto-generated>
// ------------------------------------------------------------------------------

#region Designer generated code
#pragma warning disable

namespace YourNamespace
{
	using WebAutomation.Core.WebObjects.Common.Attributes;
	using WebAutomation.Core.WebObjects.WebComponents;
	using WebAutomation.Core.WebObjects.WebComponents.Attributes;
	using WebAutomation.Core.WebObjects.WebContainer;
	using WebAutomation.Core.WebObjects.WebContainer.Attributes;

	[Name("YoutubePage")]
	public partial class YoutubePage 
	{
		[Name("SearchInput")]
		[Id("masthead-search-term")]
		[AssertPresent]
		public IWebComponent SearchInput { get; set; }

		[Name("OkButton")]
		[Xpath("//*[@id='search-btn']/span")]
		public IWebComponent OkButton { get; set; }

	}

	[Name("YoutubeSearchResultPage")]
	public partial class YoutubeSearchResultPage : YoutubePage
	{
		[Name("Link")]
		[Pxpath("//a[@title='{0}']")]
		public IWebComponent Link { get; set; }

	}

	[Name("YoutubePlayerPage")]
	public partial class YoutubePlayerPage : YoutubePage
	{
		[Name("Player")]
		[Id("player-api")]
		public IWebComponent Player { get; set; }

	}

}

#pragma warning restore
#endregion

